/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/workorders/{workorder_id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Heartbeat Lock */
        put: operations["heartbeat_lock_api_workorders__workorder_id__lock_put"];
        /** Acquire Lock */
        post: operations["acquire_lock_api_workorders__workorder_id__lock_post"];
        /** Release Lock */
        delete: operations["release_lock_api_workorders__workorder_id__lock_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workorders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workorders */
        get: operations["list_workorders_api_workorders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workorders/{workorder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workorder */
        get: operations["get_workorder_api_workorders__workorder_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workorders/{workorder_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Workorder */
        post: operations["review_workorder_api_workorders__workorder_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workorders/{workorder_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Workorder
         * @description 确认提交：审核通过后本地落库，后台异步同步至销售易。
         */
        post: operations["confirm_workorder_api_workorders__workorder_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workorders/{workorder_id}/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Logs */
        get: operations["get_audit_logs_api_workorders__workorder_id__audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditLogEntry */
        AuditLogEntry: {
            /** Session Id */
            session_id: string;
            /** Operator Name */
            operator_name: string;
            /** Operated At */
            operated_at: string;
            /** Changes */
            changes: components["schemas"]["FieldChange"][];
        };
        /**
         * ConfirmRequest
         * @description 确认提交请求 — 新增 idempotency_key 用于销售易幂等去重。
         */
        ConfirmRequest: {
            /** Session Id */
            session_id: string;
            /** Version */
            version: number;
            /**
             * Changes
             * @default []
             */
            changes: components["schemas"]["FieldChange"][];
            /** Reject Reason */
            reject_reason?: string | null;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /**
         * ConfirmResponse
         * @description 确认提交响应 — 新增 sync_status 表示销售易同步状态。
         */
        ConfirmResponse: {
            /** Review Id */
            review_id: string;
            /** Workorder Id */
            workorder_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "confirmed" | "rejected";
            /** Change Count */
            change_count: number;
            /** Bad Case Count */
            bad_case_count: number;
            /** Next Status */
            next_status: string;
            /**
             * Sync Status
             * @default pending
             * @enum {string}
             */
            sync_status: "pending" | "synced" | "failed";
        };
        /** FieldChange */
        FieldChange: {
            /**
             * Op
             * @enum {string}
             */
            op: "replace" | "add" | "remove";
            /** Path */
            path: string;
            /** Field Label */
            field_label: string;
            /** Old Value */
            old_value?: unknown | null;
            /** New Value */
            new_value?: unknown | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LockStatus
         * @description Response for lock acquire / release / heartbeat endpoints.
         */
        LockStatus: {
            /** Locked */
            locked?: boolean | null;
            /** Owner */
            owner?: string | null;
            /** Locked Minutes */
            locked_minutes?: number | null;
            /** Status */
            status?: string | null;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** Session Id */
            session_id: string;
            /** Version */
            version: number;
            /**
             * Changes
             * @default []
             */
            changes: components["schemas"]["FieldChange"][];
            /** Reject Reason */
            reject_reason?: string | null;
        };
        /** ReviewResponse */
        ReviewResponse: {
            /** Review Id */
            review_id: string;
            /** Workorder Id */
            workorder_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "confirmed" | "rejected";
            /** Change Count */
            change_count: number;
            /** Bad Case Count */
            bad_case_count: number;
            /** Next Status */
            next_status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkOrderResponse
         * @description Response for GET /api/workorders/{id} — mirrors frontend WorkOrderData.
         */
        WorkOrderResponse: {
            /** Id */
            id: string;
            /** Version */
            version: number;
            /** Status */
            status?: string | null;
            /**
             * Reject Count
             * @default 0
             */
            reject_count: number;
            /** Last Reject Reason */
            last_reject_reason?: string | null;
            /** Last Rejected By */
            last_rejected_by?: string | null;
            /** Last Rejected At */
            last_rejected_at?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Initiator */
            initiator?: string | null;
            /** Initiator Department */
            initiator_department?: string | null;
            /** Station Name */
            station_name?: string | null;
            /** Dispatch Name */
            dispatch_name?: string | null;
            /** Project Code */
            project_code?: string | null;
            /** Project Name */
            project_name?: string | null;
            /** Project Province */
            project_province?: string | null;
            /** Customer Name */
            customer_name?: string | null;
            /** Problem Description */
            problem_description?: string | null;
            /** Feedback Channel */
            feedback_channel?: string | null;
            /** Product Line */
            product_line?: string | null;
            /** Product Category */
            product_category?: string | null;
            /** Product Type */
            product_type?: string | null;
            /** Customer Level */
            customer_level?: string | null;
            /** Problem Category L1 */
            problem_category_l1?: string | null;
            /** Problem Category L2 */
            problem_category_l2?: string | null;
            /** Problem Category L3 */
            problem_category_l3?: string | null;
            /** Order Type */
            order_type?: string | null;
            /** Problem Type */
            problem_type?: string | null;
            /** Fault Category */
            fault_category?: string | null;
            /** Fault Detail */
            fault_detail?: string | null;
            /** Responsible Person */
            responsible_person?: string | null;
            /** Responsible Department */
            responsible_department?: string | null;
            /** Primary Department */
            primary_department?: string | null;
            /** After Sales Person */
            after_sales_person?: string | null;
            /** Transferred Person */
            transferred_person?: string | null;
            /** Transferred Department */
            transferred_department?: string | null;
            /** Order Level */
            order_level?: string | null;
            /** Fault Level */
            fault_level?: string | null;
            /** Onsite Level */
            onsite_level?: string | null;
            /** Required Solve Time */
            required_solve_time?: string | null;
        };
        /**
         * WorkOrderSummary
         * @description Summary row for GET /api/workorders list.
         */
        WorkOrderSummary: {
            /** Id */
            id: string;
            /** Serial Number */
            serial_number?: string | null;
            /** Station Name */
            station_name?: string | null;
            /** Status */
            status?: string | null;
            /** Customer Name */
            customer_name?: string | null;
            /** Created At */
            created_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    heartbeat_lock_api_workorders__workorder_id__lock_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workorder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acquire_lock_api_workorders__workorder_id__lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workorder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_lock_api_workorders__workorder_id__lock_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workorder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workorders_api_workorders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrderSummary"][];
                };
            };
        };
    };
    get_workorder_api_workorders__workorder_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workorder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_workorder_api_workorders__workorder_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workorder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_workorder_api_workorders__workorder_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workorder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_logs_api_workorders__workorder_id__audit_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workorder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
