"""add review audit tables

Revision ID: b36e5bd808d6
Revises: 
Create Date: 2026-07-17 10:39:44.873982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36e5bd808d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workorder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=3), nullable=True),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reject_count', sa.Integer(), nullable=False),
    sa.Column('last_reject_reason', sa.Text(), nullable=True),
    sa.Column('last_rejected_by', sa.String(length=64), nullable=True),
    sa.Column('last_rejected_at', sa.DateTime(timezone=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workorder_audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workorder_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('field_path', sa.String(length=128), nullable=False),
    sa.Column('field_label', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('ai_confidence', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('operator_name', sa.String(length=64), nullable=True),
    sa.Column('operated_at', sa.DateTime(timezone=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operated_at', 'workorder_audit_log', ['operated_at'], unique=False)
    op.create_index('idx_operator', 'workorder_audit_log', ['operator_id'], unique=False)
    op.create_index('idx_session', 'workorder_audit_log', ['session_id'], unique=False)
    op.create_index('idx_workorder', 'workorder_audit_log', ['workorder_id'], unique=False)
    op.create_table('bad_case_sample',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workorder_id', sa.String(length=64), nullable=False),
    sa.Column('audit_log_id', sa.BigInteger(), nullable=False),
    sa.Column('field_path', sa.String(length=128), nullable=False),
    sa.Column('ai_value', sa.Text(), nullable=True),
    sa.Column('human_value', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('sample_status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.ForeignKeyConstraint(['audit_log_id'], ['workorder_audit_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status', 'bad_case_sample', ['sample_status'], unique=False)
    op.create_index('idx_badcase_workorder', 'bad_case_sample', ['workorder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_badcase_workorder', table_name='bad_case_sample')
    op.drop_index('idx_status', table_name='bad_case_sample')
    op.drop_table('bad_case_sample')
    op.drop_index('idx_workorder', table_name='workorder_audit_log')
    op.drop_index('idx_session', table_name='workorder_audit_log')
    op.drop_index('idx_operator', table_name='workorder_audit_log')
    op.drop_index('idx_operated_at', table_name='workorder_audit_log')
    op.drop_table('workorder_audit_log')
    op.drop_table('workorder')
    # ### end Alembic commands ###
